### ISSUE TITLE
Versioned release

### ISSUE THREAD

**Issue by mjpost** [wmt-conference/wmt23-news-systems#2]
Can you do a versioned release (as was done [last year](https://github.com/wmt-conference/wmt22-news-systems/archive/refs/tags/v1.1.tar.gz)) so that I can incorporate this into sacrebleu?

**Comment by kocmitom** [comment]
is this what are you looking for? https://github.com/wmt-conference/wmt23-news-systems/releases/tag/v.0.1

**Comment by mjpost** [comment]
Yes, thank you!
